python datafree_kd.py \
--method probkd \
--dataset cifar10 \
--batch_size 256 \
--teacher resnet34 \
--student resnet18 \
--lr 0.1 \
--epochs 250 \
--kd_steps 10 \
--ep_steps 400 \
--g_steps 2 \
--lr_g 0.0003 \
--adv 1 \
--depth 2 \
--T 20 \
--lmda_ent 20 \
--oh 1 \
--act 0.001 \
--gpu 1 \
--seed 0 \
--save_dir run/probkd \
--log_tag probkd_L2_line34 \
--data_root /data/lijingru/cifar10/ \
--cond \
--loss kl
# --resume /data/lijingru/DataFree/checkpoints/datafree-probkd/cifar10-resnet34-resnet18--probkd_dcgan_L2_adv_testrelu2.pth